### PR TITLE
WIP: Azure Function Deployment Slot

### LINKED ISSUE #372: Azure Function Slot Deployment
# This is a Feature Proposal

## Description

- [Slots](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots) are instrumental in any sort of canary/blue-green deployment scenario. We want to support slot deployment and slot swapping
- Slots should be configurable via both `serverless.yml` and the CLI.

### Serverless.yml Configuration

```yml
...
provider:
  deployment:
    slot:
      name: {slotName}
      # Swaps slots as soon as deployment has finished, default false
      autoSwap: {true|false}
      # Defines rule for progressively swapping slot (mutually exclusive with `autoSwap`)
      # Increase traffic to slot by 5% every 10 minutes until at 50%, then swap completely
      progressiveSwap: 5 10 50
...
```
This would assume that deployments are always targeting a slot. It would allow users to never actually deploy to production, but instead deploy to a slot and test first to improve reliability. Azure functions handles "deployment" to production by just running a swap

### CLI Configuration

```bash
$ sls deploy --slot {slotName} --autoSwap {true|false} --progressiveSwap "5 10 50"
```

Also, there should be a CLI command for swapping slots:

```bash
$ sls swap slot --from staging --target production
```

Totally open to feedback on configuration values/names.

Similar or dependent issues:

- #297

### PR DESCRIPTION
**Pull request by engineersamuel**
## What did you implement:

Closes #372

## How did you implement it:

* Default the slot to 'staging' in the DeploymentConfig
* Append the slot name to to the function name in the ARM template
* Allow the user to override the slot name --slot <name>

## How can we verify it:

* Generate a new functions project and deploy, the default deploy should be staging
* TBD: Now deploy to the production slot with --slot production

## Todos:

_**Note: Run `npm run test:ci` to run all validation checks on proposed changes**_

- [ ] Ensure there are no lint errors.  
       **Validate via `npm run lint`**  
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [ ] Write tests and confirm existing functionality is not broken.  
       **Validate via `npm test`**
- [ ] Write documentation
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

**_Is this ready for review?:_** NO  
**_Is it a breaking change?:_** NO

### CODE REVIEW

**Comment by tbarlow12** [comment]
@engineersamuel what's the status on this? Still WIP? Were you able to deploy to a slot?

**Comment by engineersamuel** [comment]
> @engineersamuel what's the status on this? Still WIP? Were you able to deploy to a slot?

Just pushed some of the latest work I have here.  It does deploy to the given slot, however I believe this may be specific to the consumption plan.  I haven't tested this on premium functions, but maybe that is out of scope for this PR?  Also the Github build is failing:

```
src/plugins/deploy/azureDeployPlugin.ts(127,22): error TS2339: Property 'slot' does not exist on type 'AzureLoginOptions'.
src/plugins/deploy/azureDeployPlugin.ts(127,95): error TS2339: Property 'slot' does not exist on type 'AzureLoginOptions'.
src/plugins/deploy/azureDeployPlugin.ts(127,117): error TS2339: Property 'slot' does not exist on type 'AzureLoginOptions'.
src/plugins/deploy/azureDeployPlugin.ts(128,75): error TS2339: Property 'slot' does not exist on type 'AzureLoginOptions'.
src/plugins/deploy/azureDeployPlugin.ts(130,121): error TS2339: Property 'slot' does not exist on type 'AzureLoginOptions'.
```

However `tsc` and `npm run test` work fine locally, is there something specific to the Github build I need to do here?

**Comment by zsolt-halo** [comment]
Is this going to be resolved in the near future :)? (developing custom workaround if not)

**Comment by tbarlow12** [comment]
@engineersamuel we will be retiring the `dev` branch for now, since our team is not actively working on this project and don't have time to maintain any semblance of git flow. This will allow the community to make PRs directly against master and speed up our release cycle. Thanks for your contribution! Feel free to rebase and re-open against master if you'd like

**Pull request closed without merging**
